services:
  loan-apps:
    image: cgitdev/loan-apps-services:v23
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI
      - MYSQL_URI        
      - MYSQL_USN
      - MYSQL_PWD
      - MYSQL_DB_PROD
      - MYSQL_DB_TEST
      - PORT
      - JWT_SECRET
      - CRYPT_KEY
      - CRYPT_IV
      - MINIO_ENDPOINT
      - MINIO_PORT
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - BACKEND_URI
      - NOTIFICATION_SERVICE_URL
      - TZ
    restart: always
    networks:
      - ssot-config_default
      - mysql_cg-db-prod-connection

  loan-app-ui:
    image: cgitdev/loan-apps-ui:v15
    ports:
      - "8601:8601"
    environment:
      - BACKEND_URL=http://192.182.6.202:8000/api-v1/loan-app
    restart: always
    networks:
      - ssot-config_default

networks:
  ssot-config_default:
    external: true
  mysql_cg-db-prod-connection:
    external: true
